### ISSUE TITLE
Public Schedule API

### ISSUE THREAD

**Issue by benrick** [DevChatter/DevStreams#19]
Provide basic Public API Access for Schedule Information, so channels' bots can call it for schedule info.

Example:

`/api/Schedule/DevChatter` might return the default recurrence for DevChatter in EST/EDT.
`/api/Schedule/DevChatter?tz=America/Chicago` might return the schedule in CST/CDT.

**Comment by essenbee** [comment]
Some of this can be handled by the GraphQL endpoint #49 , but I will need to investigate the time zone conversions piece.

**Comment by essenbee** [comment]
I think this issue can be closed now, as the GraphQL endpoint covers this functionality and more
