### ISSUE TITLE
Simple Theme

### ISSUE THREAD

**Issue by benrick** [DevChatter/DevStreams#24]
We should make or find a simple theme for the site, so it will look nice when deployed.

**Comment by essenbee** [comment]
I will look at making the site themable

**Comment by essenbee** [comment]
I have made some progress on this issue, adding a **theme selector** and a couple of dark themes. The themes are from Bootswatch and are for Bootstrap 3.3.7, which is the version the site is using. If we update Bootstrap, the theme CSS files will also need updating.

I still want to do some styling of the theme selector.

**Comment by benrick** [comment]
Resolved by Essenbee's PR #27
