### ISSUE TITLE
Add a Cookie Policy Description

### ISSUE THREAD

**Issue by benrick** [DevChatter/DevStreams#28]
We need to create a cookie policy description in our `_CookieConsentPartial.cshtml` file.

I believe that our current cookies are to maintain auth and track your theme choice.

Helpful info:
https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.2

**Comment by Xunjin** [comment]
When you click at Learn More in `_CookieConsentPartial.cshtml` it does lead you to a "Lore Ipsum" Privacy Police page. It seems we need to create one too, maybe a brief introduction leading to Privacy Page where we do explain which cookies are used and why would be great ?!
