### ISSUE TITLE
Add the ability to see how long a streamer has been live

### ISSUE THREAD

**Issue by kphillpotts** [DevChatter/DevStreams#58]
By being able to see how long a streamer has been live, it is possible to see whether it is worth joining (or raiding) the channel based on how long it's probably got left.

For extra coolness, there could be an analysis of how long the streamer "normally" streams for to provide an estimate of how much time is left.  (although, that may prove to be wildly inaccurate).

**Comment by essenbee** [comment]
Great idea @kphillpotts ! We can add this to the GraphQL API as well, but subsequent to delivering the initial GraphQL PR.

**Comment by benrick** [comment]
This was included as part of the home page display of live channels.
