### ISSUE TITLE
Pull Channel Image from Twitch

### ISSUE THREAD

**Issue by benrick** [DevChatter/DevStreams#66]
Pull Channel Image from Twitch and store link to it in our Twitch Channel table.

- Display it on the Channel Details Page
- Display it on the My Channel Details Page
- (optional) Link to page on Twitch site where they can edit the image.

**Comment by reillydom** [comment]
Hey guys! 
Just looking into doing this now.

More than happy to pass this over to someone else if they want to do it!

**Comment by reillydom** [comment]
Just thinking about the optional task. Should this be under the edit section for the edit page for the channel? 
I think this is the best place for it, but the model has no knowledge of the twitch model, so that might need adding as a property?
What do you guys think?

**Comment by benrick** [comment]
The idea on the optional part would be that it links to the profile location on Twitch where you can edit that image. Be sure it opens in a new link.
