### ISSUE TITLE
Hide Irrelevant Tags on Channels Page

### ISSUE THREAD

**Issue by benrick** [DevChatter/DevStreams#75]
Hide tags which don't do any filtering on the channels list page. That means if there are 10 channels displayed, and they all have the tag, don't show the tag. Clicking it would do no filtering.

**Comment by michaeljolley** [comment]
I'd love to claim this one.  Get my feet wet with Vue.  If okay I'll PR back to `benrick/ux-channels-page` since it has the latest changes for the channels page.
