### ISSUE TITLE
Register new account validation messages are inconsistent

### ISSUE THREAD

**Issue by RyannosaurusRex** [DevChatter/DevStreams#83]
### Expected
Validation messages on the Register screen should be consistent at both field-level and summary.

### Actual
Entering a short password (<6 characters) will result in inconsistent validation messages of `Password must be at least 8 characters and password must be at least 6 characters).

![register-messages](https://user-images.githubusercontent.com/438357/57388643-9ae89180-7186-11e9-9d66-9aa58a0c81e8.png)

### Notes
This looks like a good first issue candidate.

**Comment by ghost** [comment]
🖐 I'd be happy to work on this.

I believe we will be required to scaffold the Identity pages that include an `InputModel` with a `StringLength` attribute on password properties (`Account/Register` and `Account/Manage/ChangePassword`)

If anyone is aware of a more straightforward way to approach this, please let me know.

**Comment by benrick** [comment]
Sounds good @justinhhorner !
